### PR TITLE
Map Pages to Track Events

### PR DESCRIPTION
**Pull request by dominicbarnes**
This will resolve #3 while also adding appropriate tests. This implements `page()` by treating them like track events.

/cc @ndhoule @amillet89

### CODE REVIEW

**Comment by amillet89** [comment]
lgtm! remember to add metadata options as well!

**Comment by dontgitit** [comment]
Do you think you can quickly explain a few things? 

1.) Looking through the code (https://github.com/segmentio/integration/blob/master/lib/statics.js#L326) it seemed that if trackAllPages was enabled in addition to trackNamedPages/trackCategorizedPages, it would track an ADDITIONAL event with a different name. Is that correct?

2.) It seems that analytics.js will call a .page on every page load. Does this invocation get passed a "name"?

3.) We want to have the settings show up in the UI similar to how Mixpanel's works; there's an "Advanced Options" tab that includes "Track Named Pages", "Track Categorized Pages", and "Track All Pages", where the first two are checked by default. How do we accomplish that? For us, the settings are on the Overview tab (our integration doesn't even have an Advanced Options tab?). Additionally, we only have the first two page options and they seem to be unchecked by default. 

4.) What does the timeline between a pull request merge and a deploy look like? This branch was merged a few days ago but I believe we're still not receiving page requests. Is that because it's not turned on in settings?

**Comment by dominicbarnes** [comment]
Sorry about the delay @dontgitit, but I've just finished deploying this change!

I've configured the available settings (3) to match Mixpanel, with one slight difference: the options are found under "Advanced Options".

screen shot 2015-04-01 at 12 03 48 pm

In regards to (1) we would send an additional call, but we **don't** have the `trackAllPages` option available, so only expect named/categorized pages. Which brings me to (2) in that we do **not** automatically add a `name`, your users will need to explicitly add one themselves.

Lastly, (4) there is not a direct correlation between when we merge and when we deploy. We do generally deploy pretty quickly once something is merged in, but we also generally avoid Friday deployments.

Thanks for your patience, let us know if anything isn't working out like you'd expect it to!

**Comment by dontgitit** [comment]
First, thanks for all your help @dominicbarnes! 

I tried it out and ```.page``` calls are properly flowing to our app. The only issue I had is that I had to uncheck, save, and re-check the options (track named/categorized pages) in the advanced page before they actually started working. Is this a UI bug? 

You mentioned that "we don't have the trackAllPages option available"; do you think you can explain that? Why isn't it available? If we wanted to make it available, could we?

Thanks again!

**Comment by dominicbarnes** [comment]
@dontgitit I added those fields to the configuration late last week, (when this had been merged, but undeployed) where they were _not_ checked by default. I changed it this morning to have them checked by default instead upon your request. It's likely that because you had already set up configuration previously, it kept those old defaults. Either way, if you open a new project and inspect the settings now, they will be properly checked. (I tested that out this morning as well)

I have added the `trackAllPages` option now as well. (it will be turned **off** by default)

**Comment by dontgitit** [comment]
Thanks, I see the ```trackAllPages``` option now!

With respect to the defaults, they were already checked for me, but it wasn't working until I re-checked them.

**Pull request merged**
