### PR TITLE
include campaignId and templateId for trackPurchase

### PR DESCRIPTION
**Pull request by dontgitit**

### CODE REVIEW

**Comment by dontgitit** [comment]
Hey guys, anyone able to take a look?

**Comment by f2prateek** [comment]
LGTM, can you send me a link to iterable's docs so I can verify this is in the right format?

**Comment by dontgitit** [comment]
yep, this is the call in question: http://api.iterable.com/api/docs#!/commerce/trackPurchase_post_0

**Comment by f2prateek** [comment]
LGTM

**Comment by dontgitit** [comment]
thanks!

**Pull request merged**
