### PR TITLE
Pass over total and price as Numbers

### PR DESCRIPTION
**Pull request by dontgitit**
In case they're strings.

### CODE REVIEW

**Comment by f2prateek** [comment]
Needs to be squashed into a single commit.

I'm also not sure this is entirely necessary. Total is also a semantic field in our docs, and customers shoild always be sending it as a number.

**Comment by dontgitit** [comment]
How do I squash it into a single commit?

They should, but we have a customer trying to onboard for whom our integration is breaking because they're using strings instead of numbers.

**Comment by f2prateek** [comment]
@dontgitit In that case you should ask them to send it as a number.

**Comment by dontgitit** [comment]
Sure.

**Pull request closed without merging**
