### PR TITLE
lift restriction to require userId; require either userId or email

### PR DESCRIPTION
**Pull request by dontgitit**

### CODE REVIEW

**Comment by hankim813** [comment]
@dontgitit lgtm! 

@f2prateek can you confirm one last time and merge?

**Comment by hankim813** [comment]
@dontgitit we're rolling this back for now because there's a bug and it blew up our alerts channel. 

looks like it's because `.page()` events don't have the `.email()` facade helper method so we were getting hit with `"message": "Object #<Page> has no method 'email'",`

my fault for not catching that. we want to use this:

```javascript
Iterable.ensure(function(msg, settings){
  if (msg.userId() || msg.proxy('context.traits.email') || msg.proxy('traits.email') || msg.proxy('properties.email')) return;
   return this.reject('Must set either userId or email');
 });
```
@dontgitit could you resubmit a new PR with the correct changes and add a unit tests for `.page()` calls as well? 

@f2prateek

**Comment by f2prateek** [comment]
@hankim813 maybe lets just add email to the page facade?

**Comment by calvinfo** [comment]
Agreed that's better. Another solution would be to check that it's actually a method `msg.email && msg.email()`, but I think adding to facade makes sense here.

**Comment by dontgitit** [comment]
Whoops, sorry about that! I figured all events, even things like ```.page()```, were just mapped to ```.track()``` calls under the hood... 

I'll take @hankim813 's solution for now.

**Comment by hankim813** [comment]
@dontgitit no worries it's our fault for not catching! We're actually going to release the helper method for `.page()` and `.screen()` so don't worry about it! I'll make a new PR for this afterwards :)

**Comment by dontgitit** [comment]
Awesome, thanks!!!

**Comment by dontgitit** [comment]
Can you let me know after the new stuff is deployed? Thanks again for all the help with this!

**Comment by hankim813** [comment]
@dontgitit This should be all deployed!

**Comment by dontgitit** [comment]
Awesome, thanks again!

**Pull request merged**
